### ISSUE TITLE
SystemMessageAction.java

### ISSUE THREAD

**Issue by Wrekky** [ccosp/open-o#18]
src/main/java/org/caisi/core/web/SystemMessageAction.java

22-May-2024 19:03:36.746 SEVERE [http-nio-8080-exec-8] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [action] in context with path [/oscar] threw exception [javax.servlet.ServletException: java.lang.NullPointerException] with root cause
	java.lang.NullPointerException
		at org.caisi.core.web.SystemMessageAction.view(SystemMessageAction.java:109)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.apache.struts.actions.DispatchAction.dispatchMethod(DispatchAction.java:274)
		at org.apache.struts.actions.DispatchAction.execute(DispatchAction.java:194)
		at org.springframework.web.struts.DelegatingActionProxy.execute(DelegatingActionProxy.java:110)
		at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:419)
		at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:224)
		at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1194)
		at org.apache.struts.action.ActionServlet.doGet(ActionServlet.java:414)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.oscarehr.app.XforwardHeaderFilter.doFilter(XforwardHeaderFilter.java:41)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.owasp.esapi.filters.ClickjackFilter.doFilter(ClickjackFilter.java:98)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.oscarehr.app.OscarCsrfGuardFilter.doFilter(OscarCsrfGuardFilter.java:125)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at oscar.oscarSecurity.LoginFilter.doFilter(LoginFilter.java:204)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.displaytag.filter.ResponseOverrideFilter.doFilter(ResponseOverrideFilter.java:125)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.oscarehr.util.LoggedInUserFilter.doFilter(LoggedInUserFilter.java:56)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.oscarehr.util.DbConnectionFilter.doFilter(DbConnectionFilter.java:66)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.oscarehr.util.UserActivityFilter.doFilter(UserActivityFilter.java:88)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.oscarehr.common.printing.PrivacyStatementAppendingFilter.doFilter(PrivacyStatementAppendingFilter.java:121)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.oscarehr.util.ResponseDefaultsFilter.doFilter(ResponseDefaultsFilter.java:102)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:239)
		at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:215)

**Comment by ayushkaneria** [comment]
Creted new bean of systemMessageDao:
`<bean id="systemMessageDao" class="org.oscarehr.common.dao.SystemMessageDaoImpl" autowire="byName" />`

**Comment by ayushkaneria** [comment]
Bean creation of  systemMessageDao resolved the error
